// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDYa0q1rgrez7uN77UbEBe0VcWHAO1i4',
    appId: '1:718293653182:web:8bc64365fdd3005f3b70ef',
    messagingSenderId: '718293653182',
    projectId: 'profinder-50344',
    authDomain: 'profinder-50344.firebaseapp.com',
    storageBucket: 'profinder-50344.firebasestorage.app',
    measurementId: 'G-HKV7V00PHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcIhvjt7sJ79uruKMmq-1yxWowgVejBJ8',
    appId: '1:718293653182:android:a42c1a130933f37b3b70ef',
    messagingSenderId: '718293653182',
    projectId: 'profinder-50344',
    storageBucket: 'profinder-50344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLJx59ATWEiuBzjwP7q8K8jpgzdl9wWQ',
    appId: '1:718293653182:ios:b282ac7a1260220a3b70ef',
    messagingSenderId: '718293653182',
    projectId: 'profinder-50344',
    storageBucket: 'profinder-50344.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLJx59ATWEiuBzjwP7q8K8jpgzdl9wWQ',
    appId: '1:718293653182:ios:b282ac7a1260220a3b70ef',
    messagingSenderId: '718293653182',
    projectId: 'profinder-50344',
    storageBucket: 'profinder-50344.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwDYa0q1rgrez7uN77UbEBe0VcWHAO1i4',
    appId: '1:718293653182:web:7cdc029d6f36c68c3b70ef',
    messagingSenderId: '718293653182',
    projectId: 'profinder-50344',
    authDomain: 'profinder-50344.firebaseapp.com',
    storageBucket: 'profinder-50344.firebasestorage.app',
    measurementId: 'G-E1DJGKH74H',
  );
}
